language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.6.1
  - DJANGO=1.5.1
  - DJANGO=1.4.5

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.5

install:
  - pip install Django==$DJANGO times
  - python setup.py install

script:
  - `which django-admin.py` test django_rq --settings=django_rq.test_settings --pythonpath=.
services: redis
