language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO=3.0
  - DJANGO=2.2
  - DJANGO=2.1
  - DJANGO=2.0.8
  - DJANGO=1.9.9
  - DJANGO=1.8.18
  - DJANGO=1.10.8
  - DJANGO=1.11.16

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=3.0
    - python: "2.7"
      env: DJANGO=2.2
    - python: "2.7"
      env: DJANGO=2.1
    - python: "2.7"
      env: DJANGO=2.0.8
    - python: "3.7"
      env: DJANGO=1.9.9
    - python: "3.7"
      env: DJANGO=1.8.18
    - python: "3.7"
      env: DJANGO=1.10.8
    - python: "3.7"
      env: DJANGO=1.11.16

install:
  - pip install Django==$DJANGO docutils pygments rq-scheduler django-redis
  - python setup.py install
  - pip install codecov

script: make test
services: redis

after_success:
  - codecov
